"""
JSON schema definition for Study Pack output.

Defines the expected structure of a Study Pack generated by the LLM,
used for both prompting and validation.
"""

from dataclasses import dataclass, field
from typing import List, Optional

from jsonschema import Draft202012Validator

# Maximum constraints for Study Pack output
MAX_KEY_POINTS = 5
MAX_KEYWORDS = 8
MAX_QUESTIONS = 5


@dataclass
class Citation:
    """A reference to a specific paragraph in a transcript."""
    code: str  # e.g., "T01-005"
    text_preview: str  # First ~100 chars of the cited paragraph


@dataclass
class KeyPoint:
    """A key point extracted from the transcript."""
    content: str
    citations: List[str]


@dataclass
class ActiveRecallQuestion:
    """An active recall question with hidden answer and citations."""
    question: str
    answer: str
    citations: List[str]


@dataclass
class StudyPack:
    """Complete Study Pack output structure."""
    transcript_id: str  # e.g., "transcript-10-clean"
    transcript_title: str
    objective: str  # e.g., "Ôn quiz trong 10 phút"
    key_points: List[KeyPoint]
    keywords: List[str]
    questions: List[ActiveRecallQuestion]
    warnings: List[str] = field(default_factory=list)  # Low-confidence notes
    generation_trace_id: Optional[str] = None


# JSON schema for LLM output validation
STUDY_PACK_JSON_SCHEMA = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "required": ["key_points", "keywords", "questions"],
    "additionalProperties": False,
    "properties": {
        "key_points": {
            "type": "array",
            "minItems": 1,
            "maxItems": MAX_KEY_POINTS,
            "items": {
                "type": "object",
                "required": ["content", "citations"],
                "additionalProperties": False,
                "properties": {
                    "content": {
                        "type": "string",
                        "minLength": 1,
                        "description": "Một mệnh đề kiến thức trọng tâm của buổi học."
                    },
                    "citations": {
                        "type": "array",
                        "minItems": 1,
                        "uniqueItems": True,
                        "items": {
                            "type": "string",
                            "pattern": r"^T\d{2}-\d{3}$",
                            "description": "Mã đoạn transcript, ví dụ T01-005"
                        }
                    }
                }
            }
        },
        "keywords": {
            "type": "array",
            "minItems": 1,
            "maxItems": MAX_KEYWORDS,
            "items": {
                "type": "string",
                "minLength": 1,
                "description": "Keyword quan trọng cần nhớ"
            }
        },
        "questions": {
            "type": "array",
            "minItems": 1,
            "maxItems": MAX_QUESTIONS,
            "items": {
                "type": "object",
                "required": ["question", "answer", "citations"],
                "additionalProperties": False,
                "properties": {
                    "question": {
                        "type": "string",
                        "minLength": 1,
                        "description": "Câu hỏi active recall yêu cầu tự nhớ/giải thích/áp dụng"
                    },
                    "answer": {
                        "type": "string",
                        "minLength": 1,
                        "description": "Đáp án dựa trên nội dung transcript"
                    },
                    "citations": {
                        "type": "array",
                        "minItems": 1,
                        "uniqueItems": True,
                        "items": {
                            "type": "string",
                            "pattern": r"^T\d{2}-\d{3}$"
                        }
                    }
                }
            }
        }
    }
}


_STUDY_PACK_VALIDATOR = Draft202012Validator(STUDY_PACK_JSON_SCHEMA)


def validate_study_pack_output(output: object) -> None:
    """Raise ValueError with all schema violations in an LLM response."""
    errors = sorted(
        _STUDY_PACK_VALIDATOR.iter_errors(output),
        key=lambda error: [str(part) for part in error.absolute_path],
    )
    if not errors:
        return

    messages = []
    for error in errors:
        path = '.'.join(str(part) for part in error.absolute_path) or '<root>'
        messages.append(f"{path}: {error.message}")
    raise ValueError("Study Pack JSON schema validation failed: " + '; '.join(messages))
